name: swami_ai
description: A minimalistic AI chatbot application

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.24.0"

dependencies:
  flutter:
    sdk: flutter
  
  # HTTP client for API calls
  http: ^1.1.0
  
  # WebSocket support
  web_socket_channel: ^2.4.0
  
  # Material Design icons
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/