services:
  # Weaviate Vector Database
  weaviate:
    command:
    - --host
    - 0.0.0.0
    - --port
    - '8080'
    - --scheme
    - http
    image: cr.weaviate.io/semitechnologies/weaviate:1.32.4
    ports:
    - 8080:8080
    - 50051:50051
    restart: on-failure:0
    environment:
      QUERY_DEFAULTS_LIMIT: 25
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: 'true'
      PERSISTENCE_DATA_PATH: '/var/lib/weaviate'
      ENABLE_API_BASED_MODULES: 'true'
      CLUSTER_HOSTNAME: 'node1'
      # ENABLE_MODULES: 'text2vec-transformers'
      # TRANSFORMERS_INFERENCE_API: 'http://host.docker.internal:8000/'
    volumes:
      - weaviate_data:/var/lib/weaviate
    healthcheck:
      test: ["CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost:8080/v1/meta || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s

  # FastAPI Backend
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - WEAVIATE_URL=http://weaviate:8080
      - TOGETHER_API_KEY=${TOGETHER_API_KEY}
    depends_on:
      weaviate:
        condition: service_healthy
    restart: unless-stopped
    volumes:
      - ./backend:/app
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Flutter Web Frontend
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    environment:
      - BACKEND_URL=${BACKEND_URL:-http://localhost:8000}
      - BACKEND_WS_URL=${BACKEND_WS_URL:-ws://localhost:8000}
    depends_on:
      - backend
    restart: unless-stopped

volumes:
  weaviate_data:

networks:
  default:
    driver: bridge